import os
import shutil

import juniper.framework.backend.plugin
import juniper.paths


maxscript_startup_lines = """
-- !Auto-generated by Juniper
( python.ExecuteFile (substituteString (getThisScriptFileName()) ".ms" ".py") )
"""

for i in range(2021, 2026):
    if(os.path.isdir(juniper.paths.root())):
        appdata_dir = os.path.join("c:\\users\\", os.getlogin(), f"appdata\\local\\autodesk\\3dsmax\\{i} - 64bit")
        if(os.path.isdir(appdata_dir)):
            startup_folder = os.path.join(appdata_dir, "ENU\\scripts\\startup")
            plugin = juniper.framework.backend.plugin.PluginManager().find_plugin("max")
            startup_script_py = os.path.join(plugin.root, "Source\\Bootstrap\\__bootstrap__.py")
            if(not os.path.isdir(startup_folder)):
                os.mkdir(startup_folder)

            with open(os.path.join(startup_folder, "__juniper_startup__.ms"), "w") as f:
                f.write(maxscript_startup_lines)

            shutil.copyfile(startup_script_py, os.path.join(startup_folder, "__juniper_startup__.py"))


print(os.path.join(startup_folder, "__juniper_startup__.ms"))