import os
import shutil

import juniper.paths


maxscript_startup_lines = """
-- !Auto-generated by Juniper
( python.ExecuteFile (substituteString (getThisScriptFileName()) ".ms" ".py") )
"""

for i in range(2021, 2026):
    if(os.path.isdir(juniper.paths.root())):
        appdata_dir = os.path.join("c:\\users\\", os.getlogin(), f"appdata\\local\\autodesk\\3dsmax\\{i} - 64bit")
        if(os.path.isdir(appdata_dir)):
            startup_folder = os.path.join(appdata_dir, "ENU\\scripts\\startup")
            startup_script = os.path.join(juniper.paths.root(), "scripts\\max\\startup\\__startup__.ms")
            startup_script_py = os.path.join(juniper.paths.root(), "Source\\Startup\\__startup__.max.py")
            if(not os.path.isdir(startup_folder)):
                os.mkdir(startup_folder)
            #shutil.copyfile(startup_script, os.path.join(startup_folder, "__juniper_startup__.ms"))

            with open(os.path.join(startup_folder, "__juniper_startup__.ms"), "w") as f:
                f.write(maxscript_startup_lines)

            shutil.copyfile(startup_script_py, os.path.join(startup_folder, "__juniper_startup__.py"))


print(os.path.join(startup_folder, "__juniper_startup__.ms"))