"""
Library containing various helper functions for VSCode
"""
import json
import os

import juniper.paths
import juniper.framework.backend.module


def code_workspace_path():
    """
    :return <str:path> The path to the `Juniper.code-workspace` file
    """
    return os.path.join(juniper.paths.root(), ".vscode\\Juniper.code-workspace")


def code_workspace_template_path():
    """
    :return <str:path> The path to the `code_workspace_template.json` config file
    """
    return juniper.paths.get_config("vscode\\code_workspace_template.json")


def generate_code_workspace():
    """
    Generates the `Juniper.code-workspace` file in the `.vscode` folder in juniper's workspace root
    """
    with open(code_workspace_template_path(), "r") as f:
        json_data = json.load(f)

    # Base juniper workspace
    json_data["folders"].append({
        "name": "Juniper",
        "path": juniper.paths.root()
    })

    json_data["folders"].append({
        "name": "Modules (Internal)",
        "path": os.path.join(juniper.paths.root(), "modules\\internal")
    })

    for i in juniper.paths.module_dirs(include_internal=False):
        json_data["folders"].append({
            "name": f"Module - {os.path.basename(i)}",
            "path": i
        })

    # Overriden python workspace settings
    json_data["settings"]["python.pythonPath"] = os.path.join(
        juniper.paths.root(), "bin\\common\\Python 3.7\\python.exe"
    )

    for module in juniper.framework.backend.module.ModuleManager:
        json_data["settings"]["python.analysis.extraPaths"].append(module.python_lib_dir)
        json_data["settings"]["python.analysis.extraPaths"].append(module.python_lib_external_dir)

    if(not os.path.isdir(os.path.dirname(code_workspace_path()))):
        os.makedirs(os.path.dirname(code_workspace_path()))

    with open(code_workspace_path(), "w") as f:
        f.write("// WARNING: THIS FILE IS AUTOGENERATED - ANY EDITS WILL BE OVERRIDEN\n")
        f.write("// Any per-user settings should be added to your local user workspace\n")
        f.write("// Any juniper global settings should be added to `//config/common/vscode/code_workspace_template.json`\n")
        f.writelines(json.dumps(json_data, indent=4, sort_keys=True))


generate_code_workspace()
