"""
Library containing various helper functions for VSCode
"""
import json
import os

import juniper.paths
import juniper.framework.backend.module
import juniper.framework.backend.plugin


def code_workspace_path():
    """
    :return <str:path> The path to the `Juniper.code-workspace` file
    """
    return os.path.join(juniper.paths.root(), ".vscode\\Juniper.code-workspace")


def code_workspace_template_path():
    """
    :return <str:path> The path to the `code_workspace_template.json` config file
    """
    return os.path.join(juniper.paths.root(), "Config\\VSCode\\code_workspace_template.json")


def generate_code_workspace():
    """
    Generates the `Juniper.code-workspace` file in the `.vscode` folder in juniper's workspace root
    """
    with open(code_workspace_template_path(), "r") as f:
        json_data = json.load(f)

    # Base juniper workspace
    json_data["folders"].append({
        "name": "Juniper",
        "path": juniper.paths.root()
    })

    # TODO~ Plugin sub-workspaces have been disabled as we cannot use the base code workspace settings when
    #       running scripts from them. This results in the python.exe for the Juniper workspace not being found!
    '''json_data["folders"].append({
        "name": "Plugins (All)",
        "path": os.path.join(juniper.paths.root(), "Plugins")
    })

    for plugin in juniper.framework.backend.plugin.PluginManager():
        plugin_name = f"Plugin - {plugin.display_name}"
        if(plugin.internal):
            plugin_name += " (Internal)"

        json_data["folders"].append({
            "name": plugin_name,
            "path": plugin.root
        })'''

    # Overriden python workspace settings
    json_data["settings"]["python.pythonPath"] = os.path.join(
        juniper.paths.root(), "Binaries\\Python37\\python.exe"
    )

    json_data["settings"]["python.analysis.extraPaths"].append(os.path.join(juniper.paths.root(), "Source\\Libs\\Python"))
    json_data["settings"]["python.analysis.extraPaths"].append(os.path.join(juniper.paths.root(), "Cached\\PyCache\\Python37"))

    for plugin in juniper.framework.backend.plugin.PluginManager():
        json_data["settings"]["python.analysis.extraPaths"].append(os.path.join(plugin.root, "Source\\Libs\\Python"))

    if(not os.path.isdir(os.path.dirname(code_workspace_path()))):
        os.makedirs(os.path.dirname(code_workspace_path()))

    with open(code_workspace_path(), "w") as f:
        f.write("// WARNING: THIS FILE IS AUTOGENERATED - ANY EDITS WILL BE OVERRIDEN\n")
        f.write("// Any per-user settings should be added to your local user workspace\n")
        f.write("// Any juniper global settings should be added to `//config/common/vscode/code_workspace_template.json`\n")
        f.writelines(json.dumps(json_data, indent=4, sort_keys=True))


generate_code_workspace()
